inherit_from:
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop/custom.yml
  - .rubocop_todo.yml
  - .rubocop/strict.yml

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.3
  SuggestExtensions: false

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-graphql
  - standard

inherit_gem:
  standard: config/base.yml
