AllCops:
  NewCops: disable

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard
  - ./lib/rubocop/cops

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_rails.yml
  - .rubocop_rspec.yml
  - .rubocop_strict.yml

