# fly.toml file generated for anycasts-demo on 2022-08-31T09:32:57-04:00

app = "anycasts-demo"
primary_region = "ewr"
console_command = "/rails/bin/rails console"

[build]
  dockerfile = ".fly/Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data"

[env]
  ANYCABLE_SECRET = "s3c–ØeT"
  ACTION_CABLE_ADAPTER = "any_cable"
  ANYCABLE_EMBEDDED = "true"
  ANYCABLE_BROADCAST_ADAPTER = "http"
  ANYCABLE_FLY_WS_APP_NAME = "cable"
  ANYCABLE_WEBSOCKET_URL = "wss://cable.fly.dev/cable"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
