app = "anycasts-cable"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "anycable/anycable-go:1"

[env]
  PORT = "8080"
  ANYCABLE_HOST = "0.0.0.0"
  ANYCABLE_RPC_HOST = "dns:///lhr.anycasts.internal:50051"
  ANYCABLE_TURBO_RAILS_KEY = "s3c–ØeT"
  ANYCABLE_JWT_ID_KEY = "merry-x-max"
  ANYCABLE_METRICS_HTTP = "/metrics"
  ANYCABLE_METRICS_PORT = "9091"

[metrics]
  port = 9091
  path = "/metrics"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
