# fly.toml file generated for anycasts on 2022-08-30T13:11:43-04:00

app = "anycasts"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    BUNDLER_VERSION = "2.2.33"
    NODE_VERSION = "14"
    RUBY_VERSION = "3.1.0"

[deploy]
  release_command = "bundle exec rails db:migrate"

[env]
  PORT = "8080"
  ACTION_CABLE_ADAPTER="any_cable"
  CABLE_URL="wss://anycasts-cable.fly.dev/cable"
  PERFORMANCE="true"
  SERVER_COMMAND = "bundle exec puma"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 2000
    soft_limit = 2000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
