# https://kamal-deploy.org/docs/upgrading/secrets-changes/
<% require "dotenv"; Dotenv.load(".env", overwrite: true) %>

service: anycast
image: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME") %>/anycast_demo

env:
  clear: &default_env
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: "true"
    RAILS_LOG_TO_STDOUT: "1"
    DATABASE_URL: "sqlite3:///data/db.sqlite3"

    # Anycable
    ACTION_CABLE_ADAPTER: "anycable"
    ANYCABLE_WEBSOCKET_URL: wss://<%= ENV.fetch("WS_PROXY_HOST") %>/cable
    ANYCABLE_BROADCAST_ADAPTER: http
    ANYCABLE_HTTP_BROADCAST_URL: https://<%= ENV.fetch("WS_PROXY_HOST") %>/_broadcast
  secret:
    - RAILS_MASTER_KEY
    - ANYCABLE_SECRET

servers:
  web:
    hosts: [<%= ENV.fetch("WEB_HOST") %>]
    proxy:
      host: <%= ENV.fetch("PROXY_HOST") %>
      ssl: true
      app_port: 3000
      healthcheck:
        path: /up
        interval: 1
        timeout: 5

  rpc:
    hosts: [<%= ENV.fetch("WEB_HOST") %>]
    cmd: bundle exec anycable
    env:
      clear:
        <<: *default_env
        ANYCABLE_RPC_HOST: "0.0.0.0:50051"
        ANYCABLE_DEBUG: <%= ENV.fetch("ANYCABLE_DEBUG", "1") %>
    options:
      network-alias: anycable-rpc
    proxy: false

registry:
  server: <%= ENV.fetch("KAMAL_REGISTRY_SERVER") %>
  username: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME") %>
  password: [KAMAL_REGISTRY_PASSWORD]

builder:
  context: .
  dockerfile: .fly/Dockerfile
  arch: amd64
  secrets: [RAILS_MASTER_KEY]

accessories:
  anycable-go:
    host: <%= ENV.fetch("WEB_HOST") %>
    image: anycable/anycable-go:1.6.2-alpine
    env:
      clear:
        <<: *default_env
        ANYCABLE_HOST: "0.0.0.0"
        ANYCABLE_PORT: "8080"
        ANYCABLE_HTTP_BROADCAST_PORT: "8080"
        ANYCABLE_BROKER: "memory"
        ANYCABLE_DEBUG: "1"
        ANYCABLE_BROADCAST_ADAPTER: "http"
        ANYCABLE_RPC_HOST: anycable-rpc:50051
        ANYCABLE_ALLOWED_ORIGINS: "<%= ENV.fetch("WS_ALLOWED_ORIGINS") %>"
        ANYCABLE_HEADERS: "jid"
      secret:
        - RAILS_MASTER_KEY
        - ANYCABLE_SECRET
    proxy:
      host: <%= ENV.fetch("WS_PROXY_HOST") %>
      ssl: true
      app_port: 8080
      healthcheck:
        path: /health
        interval: 1
        timeout: 5

volumes:
  - app_storage:/app/storage
  - data:/data

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
