app = "cable"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "anycable/anycable-go:1.6"
  # dockerfile = "./Dockerfile"

[env]
  PORT = "8080"
  ANYCABLE_SECRET = "s3c–ØeT"
  ANYCABLE_METRICS_HTTP = "/metrics"
  ANYCABLE_METRICS_PORT = "9091"
  ANYCABLE_HEADERS = "jid"
  ANYCABLE_BROADCAST_ADAPTER = "http"
  ANYCABLE_HTTP_BROADCAST_PORT = "8090"
  ANYCABLE_PUBSUB = "nats"
  ANYCABLE_BROKER = "memory"
  ANYCABLE_PRESENCE_TTL = "2"
  ANYCABLE_EMBED_NATS = "true"
  ANYCABLE_FLY_RPC_APP_NAME = "anycasts-demo"
  # ANYCABLE_ENATS_DEBUG = "true"
  # ANYCABLE_DEBUG = "true"
  # ANYCABLE_ENATS_GATEWAY = "nats://0.0.0.0:7222"
  # ANYCABLE_ENATS_GATEWAYS = "cable-ewr-cluster:nats://ewr.cable.internal:7222"

[metrics]
  port = 9091
  path = "/metrics"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 5000
    soft_limit = 5000
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
