name: Docs Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler: 2.3.6
      - name: Run Markdown linter
        run: |
          gem install mdl
          mdl ./**/*.md
