name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Pronto requires this
      - run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup Ruby with Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler: 2.3.6
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/linters.gemfile
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
      - name: Run Pronto
        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"
          BUNDLE_GEMFILE: gemfiles/linters.gemfile
        run: bundle exec pronto run -f github_status github_pr -c origin/${{ github.base_ref }}
