name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
        BUNDLE_GEMFILE: gemfiles/rubocop.gemfile
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby with Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler: 2.3.6
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop
