name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby with Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Start postgres
        run: sudo systemctl start postgresql.service
      - name: Run specs
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: |
          bundle exec rails db:test:prepare
          bundle exec rspec
