name: Rails Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip tests]') }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FROZEN: true
      CI: true
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Install libsqlite3
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Prepare app
        run: |
          bundle exec rails db:test:prepare
          bundle exec rails assets:precompile
      - name: Run tests
        run: |
          bundle exec rspec
